import { StyleSheet } from 'react-native';
import { ThemeStyle } from '../../global-style';

const createStyles = (theme: ThemeStyle) => {
	return StyleSheet.create({
		container: {
			flex: 1,
			backgroundColor: theme.backgroundColor,
		},
		tabBar: {
			flexDirection: 'row',
			backgroundColor: theme.backgroundColor2,
			borderBottomWidth: 1,
			borderBottomColor: theme.dividerColor,
		},
		tab: {
			flex: 1,
			paddingVertical: 10,
			alignItems: 'center',
		},
		activeTab: {
			borderBottomWidth: 3,
			borderBottomColor: theme.color4,
		},
		tabText: {
			fontSize: 13,
			color: theme.colorFaded,
			fontWeight: '500',
		},
		activeTabText: {
			color: theme.color4,
			fontWeight: '700',
		},
		// Create View
		createContainer: {
			flex: 1,
			padding: 16,
		},
		journalIntro: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 14,
			marginBottom: 12,
			backgroundColor: theme.backgroundColor2,
		},
		journalIntroTitle: {
			fontSize: 18,
			fontWeight: '700',
			color: theme.color,
			marginBottom: 6,
		},
		journalIntroText: {
			fontSize: 13,
			color: theme.color,
			lineHeight: 20,
			marginBottom: 12,
		},
		flowSteps: {
			flexDirection: 'row',
			justifyContent: 'space-between',
		},
		flowStep: {
			width: '31%',
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 8,
			backgroundColor: theme.backgroundColor,
		},
		flowStepIndex: {
			width: 22,
			height: 22,
			borderRadius: 11,
			textAlign: 'center',
			lineHeight: 22,
			color: '#FFFFFF',
			backgroundColor: theme.color4,
			fontWeight: '700',
			marginBottom: 6,
		},
		flowStepTitle: {
			fontSize: 13,
			fontWeight: '700',
			color: theme.color,
			marginBottom: 4,
		},
		flowStepBody: {
			fontSize: 11,
			color: theme.colorFaded,
			lineHeight: 16,
		},
		textInput: {
			flex: 1,
			backgroundColor: theme.backgroundColor,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 12,
			padding: 16,
			fontSize: 16,
			color: theme.color,
			textAlignVertical: 'top',
			minHeight: 150,
		},
		toolbar: {
			flexDirection: 'row',
			paddingVertical: 10,
			borderTopWidth: 1,
			borderTopColor: theme.dividerColor,
			justifyContent: 'space-around',
		},
		toolbarButton: {
			alignItems: 'center',
			justifyContent: 'center',
			paddingHorizontal: 8,
			paddingVertical: 4,
		},
		toolbarButtonText: {
			fontSize: 10,
			color: theme.colorFaded,
			marginTop: 2,
		},
		previewSection: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 12,
			padding: 12,
			marginBottom: 8,
			backgroundColor: theme.backgroundColor2,
		},
		previewTitle: {
			fontSize: 13,
			fontWeight: '700',
			color: theme.color,
			marginBottom: 6,
		},
		previewItem: {
			fontSize: 13,
			color: theme.colorFaded,
			lineHeight: 20,
		},
		saveButton: {
			backgroundColor: theme.color4,
			borderRadius: 25,
			paddingVertical: 14,
			alignItems: 'center',
			marginTop: 12,
			marginBottom: 8,
		},
		saveButtonText: {
			color: '#FFFFFF',
			fontSize: 16,
			fontWeight: '700',
		},
		saveButtonDisabled: {
			opacity: 0.5,
		},
		// Tag Selector
		tagSection: {
			paddingVertical: 10,
		},
		tagSectionLabel: {
			fontSize: 13,
			color: theme.colorFaded,
			fontWeight: '600',
			marginBottom: 8,
		},
		tagChipsRow: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			gap: 6,
		},
		tagChip: {
			borderRadius: 16,
			paddingHorizontal: 12,
			paddingVertical: 6,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			backgroundColor: theme.backgroundColor,
		},
		tagChipSelected: {
			backgroundColor: theme.color4,
			borderColor: theme.color4,
		},
		tagChipText: {
			fontSize: 13,
			color: theme.color,
		},
		tagChipTextSelected: {
			color: '#FFFFFF',
		},
		customTagInput: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 20,
			paddingHorizontal: 14,
			paddingVertical: 8,
			fontSize: 14,
			color: theme.color,
			marginTop: 8,
		},
		// Browse View
		searchBar: {
			flexDirection: 'row',
			alignItems: 'center',
			margin: 12,
			paddingHorizontal: 14,
			paddingVertical: 8,
			borderRadius: 10,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
			borderWidth: 1,
			borderColor: theme.dividerColor,
		},
		searchInput: {
			flex: 1,
			fontSize: 15,
			color: theme.color,
			paddingVertical: 4,
			marginLeft: 8,
		},
		// Record Card
		card: {
			backgroundColor: theme.backgroundColor,
			borderRadius: 12,
			marginHorizontal: 12,
			marginVertical: 4,
			padding: 14,
			borderWidth: 1,
			borderColor: theme.dividerColor,
		},
		cardHeader: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
			marginBottom: 6,
		},
		cardTitle: {
			fontSize: 15,
			fontWeight: '600',
			color: theme.color,
			flex: 1,
		},
		cardTypeIcon: {
			fontSize: 14,
			marginLeft: 6,
		},
		cardSnippet: {
			fontSize: 13,
			color: theme.colorFaded,
			marginBottom: 8,
			lineHeight: 18,
		},
		cardReplayButton: {
			alignSelf: 'flex-start',
			borderWidth: 1,
			borderColor: theme.color4,
			borderRadius: 8,
			paddingHorizontal: 10,
			paddingVertical: 6,
			marginBottom: 8,
		},
		cardReplayButtonText: {
			color: theme.color4,
			fontSize: 12,
			fontWeight: '700',
		},
		cardFooter: {
			flexDirection: 'row',
			justifyContent: 'space-between',
			alignItems: 'center',
		},
		cardTags: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			gap: 4,
			flex: 1,
		},
		cardTag: {
			borderRadius: 10,
			paddingHorizontal: 8,
			paddingVertical: 2,
			backgroundColor: theme.backgroundColorHover4 || theme.backgroundColor3 || theme.backgroundColor,
		},
		cardTagText: {
			fontSize: 11,
			color: theme.color4,
		},
		cardTime: {
			fontSize: 11,
			color: theme.colorFaded,
		},
		emptyState: {
			flex: 1,
			justifyContent: 'center',
			alignItems: 'center',
			padding: 40,
		},
		emptyStateText: {
			fontSize: 15,
			color: theme.colorFaded,
			textAlign: 'center',
			marginTop: 12,
		},
		emptyStateIcon: {
			fontSize: 48,
			color: theme.colorFaded,
		},
		// Loading
		loadingContainer: {
			flex: 1,
			justifyContent: 'center',
			alignItems: 'center',
		},
		analysisContainer: {
			flex: 1,
			padding: 12,
		},
		recordSelector: {
			marginBottom: 10,
		},
		recordSelectorItem: {
			maxWidth: 180,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingVertical: 8,
			marginRight: 8,
			backgroundColor: theme.backgroundColor,
		},
		recordSelectorItemSelected: {
			backgroundColor: theme.color4,
			borderColor: theme.color4,
		},
		recordSelectorText: {
			fontSize: 13,
			color: theme.color,
		},
		recordSelectorTextSelected: {
			color: '#FFFFFF',
			fontWeight: '700',
		},
		primaryActionButton: {
			backgroundColor: theme.color4,
			borderRadius: 8,
			paddingVertical: 12,
			alignItems: 'center',
			marginBottom: 10,
		},
		primaryActionButtonText: {
			color: '#FFFFFF',
			fontSize: 15,
			fontWeight: '700',
		},
		secondaryActionButton: {
			flex: 1,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			paddingVertical: 10,
			alignItems: 'center',
			marginHorizontal: 4,
			backgroundColor: theme.backgroundColor,
		},
		secondaryActionButtonText: {
			color: theme.color,
			fontSize: 13,
			fontWeight: '600',
		},
		smallActionButton: {
			borderRadius: 6,
			paddingHorizontal: 8,
			paddingVertical: 5,
			backgroundColor: theme.backgroundColor2,
		},
		smallActionButtonText: {
			color: theme.color,
			fontSize: 11,
			fontWeight: '600',
		},
		analysisPanel: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 12,
			marginBottom: 10,
			backgroundColor: theme.backgroundColor,
		},
		analysisTitle: {
			fontSize: 16,
			fontWeight: '700',
			color: theme.color,
			marginBottom: 6,
		},
		analysisMeta: {
			fontSize: 12,
			color: theme.colorFaded,
		},
		analysisBody: {
			fontSize: 13,
			color: theme.color,
			lineHeight: 20,
			marginBottom: 6,
		},
		analysisListItem: {
			fontSize: 12,
			color: theme.colorFaded,
			lineHeight: 18,
			marginTop: 3,
		},
		reflectEditor: {
			minHeight: 220,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 10,
			marginTop: 6,
			marginBottom: 10,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
			color: theme.color,
			fontSize: 13,
			lineHeight: 20,
		},
		promptEditor: {
			minHeight: 140,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 10,
			marginTop: 6,
			marginBottom: 10,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
			color: theme.color,
			fontSize: 12,
			lineHeight: 18,
		},
		askInput: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			paddingHorizontal: 12,
			paddingVertical: 9,
			marginTop: 6,
			marginBottom: 10,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
			color: theme.color,
			fontSize: 14,
		},
		askAnswer: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 10,
			marginTop: 2,
			backgroundColor: theme.backgroundColor2,
			color: theme.color,
			fontSize: 13,
			lineHeight: 20,
		},
		mediaGrid: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			marginTop: 6,
			marginBottom: 6,
		},
		mediaThumbButton: {
			width: 96,
			marginRight: 8,
			marginBottom: 8,
		},
		mediaThumb: {
			width: 96,
			height: 72,
			borderRadius: 8,
			backgroundColor: theme.backgroundColor2,
		},
		mediaThumbText: {
			fontSize: 10,
			color: theme.colorFaded,
			marginTop: 3,
		},
		timeline: {
			marginTop: 8,
		},
		timelineItem: {
			flexDirection: 'row',
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 8,
			marginTop: 8,
			backgroundColor: theme.backgroundColor2,
		},
		timelineThumbButton: {
			width: 82,
			marginRight: 10,
		},
		timelineThumb: {
			width: 82,
			height: 62,
			borderRadius: 8,
			backgroundColor: theme.backgroundColor,
		},
		timelineTime: {
			fontSize: 12,
			color: theme.color4,
			fontWeight: '700',
			marginBottom: 3,
		},
		previewBackdrop: {
			flex: 1,
			backgroundColor: 'rgba(0,0,0,0.88)',
			justifyContent: 'center',
			alignItems: 'center',
			padding: 16,
		},
		previewImage: {
			width: '100%',
			height: '82%',
		},
		previewCloseText: {
			color: '#FFFFFF',
			fontSize: 15,
			fontWeight: '700',
			marginTop: 16,
		},
		mindMap: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			marginVertical: 6,
		},
		mindMapNode: {
			width: '47%',
			minHeight: 54,
			borderRadius: 8,
			borderWidth: 1,
			borderColor: theme.dividerColor,
			padding: 8,
			marginRight: 6,
			marginBottom: 6,
			justifyContent: 'center',
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
		},
		mindMapNodeRoot: {
			borderColor: theme.color4,
			backgroundColor: theme.color4,
		},
		mindMapNodeText: {
			fontSize: 12,
			color: theme.color,
			fontWeight: '600',
			textAlign: 'center',
		},
		mindMapNodeRootText: {
			color: '#FFFFFF',
		},
		mindMapRelations: {
			marginTop: 4,
		},
		mindMapRelationRow: {
			flexDirection: 'row',
			alignItems: 'center',
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 8,
			marginTop: 6,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
		},
		mindMapRelationText: {
			flex: 1,
			fontSize: 11,
			lineHeight: 16,
			color: theme.color,
		},
		mindMapRelationLabel: {
			maxWidth: 88,
			borderRadius: 10,
			paddingHorizontal: 8,
			paddingVertical: 3,
			marginHorizontal: 6,
			fontSize: 10,
			fontWeight: '700',
			color: theme.color4,
			backgroundColor: theme.backgroundColorHover4 || theme.backgroundColor,
			textAlign: 'center',
		},
		exportRow: {
			flexDirection: 'row',
			marginHorizontal: -4,
			marginBottom: 8,
		},
		materialSlide: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 10,
			marginTop: 8,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
		},
		materialSlideTitle: {
			fontSize: 13,
			fontWeight: '700',
			color: theme.color,
			marginBottom: 4,
		},
		flashcardList: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 12,
			marginTop: 4,
			marginBottom: 24,
			backgroundColor: theme.backgroundColor,
		},
		flashcardListItem: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 10,
			marginTop: 10,
			backgroundColor: theme.backgroundColor3 || theme.backgroundColor,
		},
		flashcardGroup: {
			fontSize: 10,
			color: theme.colorFaded,
			marginBottom: 4,
		},
		flashcardQuestion: {
			fontSize: 14,
			color: theme.color,
			fontWeight: '700',
			lineHeight: 20,
			marginBottom: 8,
		},
		flashcardOption: {
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			paddingHorizontal: 10,
			paddingVertical: 9,
			marginTop: 7,
			backgroundColor: theme.backgroundColor,
		},
		flashcardOptionCorrect: {
			borderColor: '#2E7D32',
			backgroundColor: '#E8F5E9',
		},
		flashcardOptionWrong: {
			borderColor: '#C62828',
			backgroundColor: '#FFEBEE',
		},
		flashcardOptionText: {
			fontSize: 12,
			color: theme.color,
			lineHeight: 18,
		},
		flashcardOptionAnswerText: {
			color: '#1F2933',
		},
		flashcardFeedback: {
			fontSize: 12,
			fontWeight: '700',
			marginTop: 8,
			lineHeight: 18,
		},
		flashcardFeedbackCorrect: {
			color: '#2E7D32',
		},
		flashcardFeedbackWrong: {
			color: '#C62828',
		},
		flashcardEmptyText: {
			textAlign: 'center',
			color: theme.colorFaded,
			fontSize: 14,
			marginVertical: 24,
		},
		dashboardHeader: {
			flexDirection: 'row',
			alignItems: 'center',
			marginBottom: 12,
		},
		dashboardIcon: {
			width: 52,
			height: 52,
			borderRadius: 8,
			borderWidth: 2,
			borderColor: theme.color4,
			marginRight: 12,
			padding: 8,
			flexDirection: 'row',
			alignItems: 'flex-end',
		},
		dashboardIconBarTall: {
			width: 8,
			height: 30,
			backgroundColor: theme.color4,
			borderRadius: 3,
			marginRight: 5,
		},
		dashboardIconBar: {
			width: 8,
			height: 20,
			backgroundColor: theme.colorFaded,
			borderRadius: 3,
			marginRight: 5,
		},
		dashboardIconDot: {
			width: 10,
			height: 10,
			borderRadius: 5,
			backgroundColor: theme.color4,
		},
		dashboardGrid: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			justifyContent: 'space-between',
			marginBottom: 10,
		},
		dashboardTile: {
			width: '48%',
			borderWidth: 1,
			borderColor: theme.dividerColor,
			borderRadius: 8,
			padding: 12,
			marginBottom: 8,
			backgroundColor: theme.backgroundColor,
		},
		dashboardTileValue: {
			fontSize: 24,
			fontWeight: '800',
			color: theme.color,
		},
		dashboardTileLabel: {
			fontSize: 12,
			color: theme.colorFaded,
			marginTop: 4,
		},
		dashboardProgressItem: {
			marginBottom: 10,
		},
		dashboardProgressLabel: {
			fontSize: 12,
			color: theme.color,
			marginBottom: 4,
		},
		dashboardProgressTrack: {
			height: 8,
			borderRadius: 4,
			backgroundColor: theme.backgroundColor2,
			overflow: 'hidden',
		},
		dashboardProgressFill: {
			height: 8,
			borderRadius: 4,
			backgroundColor: theme.color4,
		},
		wordCloud: {
			flexDirection: 'row',
			flexWrap: 'wrap',
			alignItems: 'center',
		},
		wordCloudItem: {
			color: theme.color,
			marginRight: 10,
			marginBottom: 8,
			fontWeight: '700',
		},
	});
};

export default createStyles;
